---
title: "About Me"
sidebar: false 
---

I am a 4rd year student of Industrial Engineering at Hacettepe University. Additionally, I am a graduate of Hacettepe University, Department of Electricity. I received theoretical training in Project Management, System and Process Development, Data & Business Analysis and Production Planning and provided the necessary foundation for internship and I continue my research on these subjects. I am very enthusiastic and willing to work in the internship program in order to experience real applications in the business world and to find answers to the questions in my mind, together with the skill and knowledge I have gained in these subjects. ---

# Education

-   Hacettepe University Industrial Engineering 2.64/4.00 (15.09.2019-17.06.2024 ) Ankara, Turkey
-   Hacettepe University Programme of Electricity 3.00/4.00 (5.09.2016 - 10.09.2018 ) Ankara, Turkey

# Work Experience

-   FNSS Defence Systems Inc. (10.07.2023-4.08.2023) Supply Chain Management - Internship

-   General Directorate of State Airports Authority (DHMİ) (18.10.2017-15.01.2018) Electrical and Electronic Maintenance- Internship

-   Electricity Generation Company (EÜAŞ) (12.06.2017-28.08.2017) Electrical and Electronic Maintenance- Internship

# Projects

# Competencies

R, Quarto, Git, Python , MS Excel , Solidwork , MySQL , MS Word , Power BI

# Hobbies

• Watching Movies and Series • Camping • Swimming • Listen to music • Research • Chess • PC Games • Hiking • Cooking/Making coffee
