---
title: "Assignment 1"
---

# Assignment 1

```{r}
1 + 1
```

My first assignment has four parts.

## (a) Choose a video from one of the following sources and provide a brief summary

in your Quarto document: - RStudio Global 2022 conference talks - Posit YouTube channel playlist - Any R-related video from the web or YouTube that you find interesting

THE VIDEO I SELECTED AND ITS LINK ARE MENTIONED BELOW ZJ \| Easy larger-than-RAM data manipulation with {disk.frame} \| RStudio https://youtu.be/EOjObl_GSi4?list=PL9HYL-VRX0oTOK4cpbCbRk15K2roEgzVW

SUMMARY:The main topic in the video is easy big data manipulation with "disc.frame". The reason we need this operation is that when we are dealing with large data and R tries to load the data, the data is transferred to RAM. If the data size is larger than RAM can store, we get the error "Cannot allocate vectors of size". Basically, to solve this problem, we break the whole data set into smaller chunks without loading it into memory. ''Disk.frame'' is a folder containing many ''fst'' files. We convert the data to disc.frame by specifying the path to the CSV file with the function ''csv_to_disk.frame(path_to_cvs_file1, path_to_cvs_file2,..)''. We use dplyr verbs to process the data directly. With the srckeep function we specify which columns are loaded into memory, and with the filter, mutate, group, summarise and collect commands we have the possibility to collect the data we want from large data files.

## (b) Demonstrate and explain three differences between R and Python (e.g. coding style, syntax etc.) Include coding examples using code chunks.

### 1) Coding Blocks / Conventions

R uses curly braces and parentheses. For example, if you want to use a for loop or an if statement, you must enclose the statement in parentheses and then open the curly braces to run the code.

{r} for (i in 1:5){ print("code block 1") if (i \> 3) { print("code block 2") } print("code block 1 again") }

Python on the other hand uses indentation and columns. The same R code would look like this:

for i in range(5): print("code block 1") if i \> 3: print("code block 2") print("code block 1 again")

where the indentation is very important as the different indentation levels refer to different execution levels that is a loop or an if statement only affect the indented code not the non- indented code.

### 2)Operation Spread

R: Operation can be spread on multiple rows {r} 2 + 3 + 4

output: \[1\] 9

Python: Operation on multiple rows must be declered either usıng  and ()

2 + 3 +\
4

Output:9

or

(2 + 3 + 4)

Output:9

### 3) Indexing

R: Index start's at 1 , includes last element In R indexing starts at one and ends with the last element in the sequence included.

{r} for (i in 1:10) { print(i) }

Output: \[1\] 1 \[1\] 2 \[1\] 3 \[1\] 4 \[1\] 5 \[1\] 6 \[1\] 7 \[1\] 8 \[1\] 9 \[1\] 10

Python: Index start's at 0 , doesn't include last element In Python indexing starts at zero and ends without the last element number four functions i

for i in range(10) print(i)

Output: 0 1 2 3 4 5 6 7 8 9

## **(c) Import the \"na_example\" data set from the dslabs package. Your web page should first show the content of \"na_example\" data set along with its NA values, and then, the total number of NAs. Then replace all NA values in the \"na_example\" data set with 0, and store it as a new object. After making this change, print the new data frame (the one without NAs) and the total number of NAs in this new data frame to the page. (Include R codes that will produce these outputs)**

```         
package ‘dslabs’ successfully unpacked and MD5 sums checked  The downloaded binary packages are in 	C:\Users\Monster\AppData\Local\Temp\RtmpUB0tuU\downloaded_packages 

> library(dslabs)
> data("na_example") 
> cat("Original na_example dataset:\n") 

Original na_example dataset: 
> print(na_example)    

[1]  2  1  3  2  1  3  1  4  3  2  2 NA  2  2  1  4 NA  1  1  2  1  2   [23]  2  1  2  5 NA  2  2  3  1  2  4  1  1  1  4  5  2  3  4  1  2  4   [45]  1  1  2  1  5 NA NA NA  1  1  5  1  3  1 NA  4  4  7  3  2 NA NA   [67]  1 NA  4  1  2  2  3  2  1  2  2  4  3  4  2  3  1  3  2  1  1  1   [89]  3  1 NA  3  1  2  2  1  2  2  1  1  4  1  1  2  3  3  2  2  3  3  [111]  3  4  1  1  1  2 NA  4  3  4  3  1  2  1 NA NA NA NA  1  5  1  2  [133]  1  3  5  3  2  2 NA NA NA NA  3  5  3  1  1  4  2  4  3  3 NA  2  [155]  3  2  6 NA  1  1  2  2  1  3  1  1  5 NA NA  2  4 NA  2  5  1  4  [177]  3  3 NA  4  3  1  4  1  1  3  1  1 NA NA  3  5  2  2  2  3  1  2  [199]  2  3  2  1 NA  2 NA  1 NA NA  2  1  1 NA  3 NA  1  2  2  1  3  2  [221]  2  1  1  2  3  1  1  1  4  3  4  2  2  1  4  1 NA  5  1  4 NA  3  [243] NA NA  1  1  5  2  3  3  2  4 NA  3  2  5 NA  2  3  4  6  2  2  2  [265] NA  2 NA  2 NA  3  3  2  2  4  3  1  4  2 NA  2  4 NA  6  2  3  1  [287] NA  2  2 NA  1  1  3  2  3  3  1 NA  1  4  2  1  1  3  2  1  2  3  [309]  1 NA  2  3  3  2  1  2  3  5  5  1  2  3  3  1 NA NA  1  2  4 NA  [331]  2  1  1  1  3  2  1  1  3  4 NA  1  2  1  1  3  3 NA  1  1  3  5  [353]  3  2  3  4  1  4  3  1 NA  2  1  2  2  1  2  2  6  1  2  4  5 NA  [375]  3  4  2  1  1  4  2  1  1  1  1  2  1  4  4  1  3 NA  3  3 NA  2  [397] NA  1  2  1  1  4  2  1  4  4 NA  1  2 NA  3  2  2  2  1  4  3  6  [419]  1  2  3  1  3  2  2  2  1  1  3  2  1  1  1  3  2  2 NA  4  4  4  [441]  1  1 NA  4  3 NA  1  3  1  3  2  4  2  2  2  3  2  1  4  3 NA  1  [463]  4  3  1  3  2 NA  3 NA  1  3  1  4  1  1  1  2  4  3  1  2  2  2  [485]  3  2  3  1  1 NA  3  2  1  1  2 NA  2  2  2  3  3  1  1  2 NA  1  [507]  2  1  1  3  3  1  3  1  1  1  1  1  2  5  1  1  2  2  1  1 NA  1  [529]  4  1  2  4  1  3  2 NA  1  1 NA  2  1  1  4  2  3  3  1  5  3  1  [551]  1  2 NA  1  1  3  1  3  2  4 NA  2  3  2  1  2  1  1  1  2  2  3  [573]  1  5  2 NA  2 NA  3  2  2  2  1  5  3  2  3  1 NA  3  1  2  2  2  [595]  1  2  2  4 NA  6  1  2 NA  1  1  2  2  3 NA  3  2  3  3  4  2 NA  [617]  2 NA  4 NA  1  1  2  2  3  1  1  1  3 NA  2  5 NA  7  1 NA  4  3  [639]  3  1 NA  1  1  1  1  3  2  4  2  2  3 NA NA  1  4  3  2  2  2  3  [661]  2  4  2  2  4 NA NA NA  6  3  3  1  4  4  2  1 NA  1  6 NA  3  3  [683]  2  1  1  6 NA  1  5  1 NA  2  6  2 NA  4  1  3  1  2 NA  1  1  3  [705]  1  2  4  2  1  3  2  4  3  2  2  1  1  5  6  4  2  2  2  2  4 NA  [727]  1  2  2  2  2  4  5 NA NA NA  4  3  3  3  2  4  2  4 NA NA NA NA  [749]  2  1 NA  2  4  3  2 NA  2  3  1  3  4 NA  1  2  1  2 NA  3  1  2  [771]  1  2  1  2  1  2  2  2  2  1  1  3  3  1  3  4  3 NA NA  4  2  3  [793]  2  1  3  2  4  2  2  3  1  2  4  3  3  4 NA  1  4  2  1  1  1  3  [815]  1  5  2  2  4  2 NA  1  3  1  2 NA  1  2  1  2  1 NA  1  3  2  3  [837]  2 NA  2  1  4  2 NA NA NA  2  4  2 NA NA  3  1 NA  5  5  2  2  2  [859] NA  2  1  3  1  3  2  4  2  4 NA  4  1  2  3  2  3  3  2  3  2  2  [881]  2  1  3  2  4  2 NA  3  3  2  2 NA NA  3  2  1  2  4  1  1  1  1  [903]  4  3  2 NA  3  2 NA  1 NA  3  2  1  1  1  2 NA  2  2  3  3  2 NA  [925] NA  4  5  2  2  2  1  2  3  1  3  3  4  3 NA  1  1  1 NA  4  3  5  [947]  1  1  2 NA  2  2  2  2  5  2  2  3  1  2  3 NA  1  2 NA NA  2 NA  [969]  3  1  1  2  5  3  5  1  1  4 NA  2  1  3  1  1  2  4  3  3  3 NA  [991]  1  1  2  2  1  1  2  2 NA  2 

> cat("\nNumber of NAs in the original dataset: ", sum(is.na(na_example)), "\n") 

Number of NAs in the original dataset:  145 

> na_example_no_na <- na_example > na_example_no_na[is.na(na_example_no_na)] <- 0 

> cat("\nModified na_example dataset (NAs replaced with 0):\n")  
Modified na_example dataset (NAs replaced with 0):
> print(na_example_no_na)    

[1] 2 1 3 2 1 3 1 4 3 2 2 0 2 2 1 4 0 1 1 2 1 2 2 1 2 5 0 2 2 3 1 2 4   [34] 1 1 1 4 5 2 3 4 1 2 4 1 1 2 1 5 0 0 0 1 1 5 1 3 1 0 4 4 7 3 2 0 0   [67] 1 0 4 1 2 2 3 2 1 2 2 4 3 4 2 3 1 3 2 1 1 1 3 1 0 3 1 2 2 1 2 2 1  [100] 1 4 1 1 2 3 3 2 2 3 3 3 4 1 1 1 2 0 4 3 4 3 1 2 1 0 0 0 0 1 5 1 2  [133] 1 3 5 3 2 2 0 0 0 0 3 5 3 1 1 4 2 4 3 3 0 2 3 2 6 0 1 1 2 2 1 3 1  [166] 1 5 0 0 2 4 0 2 5 1 4 3 3 0 4 3 1 4 1 1 3 1 1 0 0 3 5 2 2 2 3 1 2  [199] 2 3 2 1 0 2 0 1 0 0 2 1 1 0 3 0 1 2 2 1 3 2 2 1 1 2 3 1 1 1 4 3 4  [232] 2 2 1 4 1 0 5 1 4 0 3 0 0 1 1 5 2 3 3 2 4 0 3 2 5 0 2 3 4 6 2 2 2  [265] 0 2 0 2 0 3 3 2 2 4 3 1 4 2 0 2 4 0 6 2 3 1 0 2 2 0 1 1 3 2 3 3 1  [298] 0 1 4 2 1 1 3 2 1 2 3 1 0 2 3 3 2 1 2 3 5 5 1 2 3 3 1 0 0 1 2 4 0  [331] 2 1 1 1 3 2 1 1 3 4 0 1 2 1 1 3 3 0 1 1 3 5 3 2 3 4 1 4 3 1 0 2 1  [364] 2 2 1 2 2 6 1 2 4 5 0 3 4 2 1 1 4 2 1 1 1 1 2 1 4 4 1 3 0 3 3 0 2  [397] 0 1 2 1 1 4 2 1 4 4 0 1 2 0 3 2 2 2 1 4 3 6 1 2 3 1 3 2 2 2 1 1 3  [430] 2 1 1 1 3 2 2 0 4 4 4 1 1 0 4 3 0 1 3 1 3 2 4 2 2 2 3 2 1 4 3 0 1  [463] 4 3 1 3 2 0 3 0 1 3 1 4 1 1 1 2 4 3 1 2 2 2 3 2 3 1 1 0 3 2 1 1 2  [496] 0 2 2 2 3 3 1 1 2 0 1 2 1 1 3 3 1 3 1 1 1 1 1 2 5 1 1 2 2 1 1 0 1  [529] 4 1 2 4 1 3 2 0 1 1 0 2 1 1 4 2 3 3 1 5 3 1 1 2 0 1 1 3 1 3 2 4 0  [562] 2 3 2 1 2 1 1 1 2 2 3 1 5 2 0 2 0 3 2 2 2 1 5 3 2 3 1 0 3 1 2 2 2  [595] 1 2 2 4 0 6 1 2 0 1 1 2 2 3 0 3 2 3 3 4 2 0 2 0 4 0 1 1 2 2 3 1 1  [628] 1 3 0 2 5 0 7 1 0 4 3 3 1 0 1 1 1 1 3 2 4 2 2 3 0 0 1 4 3 2 2 2 3  [661] 2 4 2 2 4 0 0 0 6 3 3 1 4 4 2 1 0 1 6 0 3 3 2 1 1 6 0 1 5 1 0 2 6  [694] 2 0 4 1 3 1 2 0 1 1 3 1 2 4 2 1 3 2 4 3 2 2 1 1 5 6 4 2 2 2 2 4 0  [727] 1 2 2 2 2 4 5 0 0 0 4 3 3 3 2 4 2 4 0 0 0 0 2 1 0 2 4 3 2 0 2 3 1  [760] 3 4 0 1 2 1 2 0 3 1 2 1 2 1 2 1 2 2 2 2 1 1 3 3 1 3 4 3 0 0 4 2 3  [793] 2 1 3 2 4 2 2 3 1 2 4 3 3 4 0 1 4 2 1 1 1 3 1 5 2 2 4 2 0 1 3 1 2  [826] 0 1 2 1 2 1 0 1 3 2 3 2 0 2 1 4 2 0 0 0 2 4 2 0 0 3 1 0 5 5 2 2 2  [859] 0 2 1 3 1 3 2 4 2 4 0 4 1 2 3 2 3 3 2 3 2 2 2 1 3 2 4 2 0 3 3 2 2  [892] 0 0 3 2 1 2 4 1 1 1 1 4 3 2 0 3 2 0 1 0 3 2 1 1 1 2 0 2 2 3 3 2 0  [925] 0 4 5 2 2 2 1 2 3 1 3 3 4 3 0 1 1 1 0 4 3 5 1 1 2 0 2 2 2 2 5 2 2  [958] 3 1 2 3 0 1 2 0 0 2 0 3 1 1 2 5 3 5 1 1 4 0 2 1 3 1 1 2 4 3 3 3 0  [991] 1 1 2 2 1 1 2 2 0 2 

> cat("\nNumber of NAs in the modified dataset: ", sum(is.na(na_example_no_na)), "\n") 

Number of NAs in the modified dataset:  0 
```
